name: 'Setup Pierrot CLI'
description: 'Setup your runner with Pierrot CLI'
author: 'musketyr'
branding:
  icon: 'git-pull-request'
  color: 'white'
inputs:
  version:
    description: 'The version of Pierrot CLI'
    required: true
    default: '1.0.0'
  token:
    description: 'The token to be used with the Pierrot CLI'
    required: false
  organization:
    description: 'The organization to be used with the Pierrot CLI'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
